AllCops:
  DisplayCopNames: true

#
# Style
#

Style/ModuleFunction:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

#
# Metrics
#

Metrics/AbcSize:
  Max: 25

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Max: 100

Metrics/CyclomaticComplexity:
  Max: 25

Metrics/LineLength:
  Max: 128

Metrics/MethodLength:
  Max: 25

Metrics/PerceivedComplexity:
  Max: 25
