# frozen_string_literal: true

source "https://rubygems.org"
ruby RUBY_VERSION

gemspec

group :development, :test do
  gem "benchmark-ips"
  gem "guard-rspec"
  gem "rake"
  gem "rspec", "~> 3.5"
  gem "rubocop", "0.49.1"
  gem "tjson", "~> 0.5"
end
