[[example]]
name = "One unsigned integer"
description = "Single-entry message mapping ID #24 to an unsigned integer value 42"
success = true
encoded = "020355"
decoded = '{"24": 42}'

[[example]]
name = "Two unsigned integers"
description = "Two entry message mapping IDs #1 and #2 to unsigned integers 24 and 42"
success = true
encoded = "11312155"
decoded = '{"1": 24, "2": 42}'

[[example]]
name = "Trucated varint"
description = "Field identifier 1 with varint wiretype, but no value"
success = false
encoded = "08"

[[example]]
name = "Nested message with unsigned integer"
description = "Single-entry message containing another single-entry message"
success = true
encoded = "1507020355"
decoded = '{"1": {"24": 42}}'

[[example]]
name = "Truncated nested message"
description = "Single-entry message containing another single-entry message"
success = false
encoded = "15070203"

[[example]]
name = "Binary data"
description = "The ASCII string 'Hello, world!' encoded as binary data"
success = true
encoded = "171b48656c6c6f2c20776f726c6421"
decoded = '{"1": "Hello, world!"}'

[[example]]
name = "Truncated binary data"
description = "The truncated ASCII string 'Hello,'"
success = false
encoded = "171b48656c6c6f2c"
